/**
 * This file is a stub for the Convex-generated API.
 *
 * The real file is generated automatically by `npx convex dev` (or `npx convex deploy`).
 * It will be placed at: convex/_generated/api.d.ts
 *
 * DO NOT edit this file. Run `npx convex dev` from the project root to regenerate.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = new Proxy(
  {},
  {
    get: (_target, prop) =>
      new Proxy(
        {},
        {
          get: (_t, p) => `${String(prop)}.${String(p)}`,
        }
      ),
  }
)
